### ISSUE TITLE
There isn't any code

### ISSUE THREAD

**Issue by Briaoeuidhtns** [dustinc555/ReactWebApp#1]
what a bad app wow

**Comment by dustinc555** [comment]
I'm working on it. I don't currently have any React tho

**Comment by dustinc555** [comment]
There is a beutiful gitignore tho, just observe that and think of my glory

**Comment by Briaoeuidhtns** [comment]
why is the gitignore in a folder tho?

**Comment by dustinc555** [comment]
im not sure, i actually used the button in the empty dir to add it

**Comment by Briaoeuidhtns** [comment]
wow bad, can't even add your own files

**Comment by dustinc555** [comment]
what do i even pay you for

**Comment by Briaoeuidhtns** [comment]
not for good modular commit messages, that's for sure
